var minMaxFilterEditor = function (cell, onRendered, success, cancel, editorParams) {
    var end;
    var container = document.createElement("span");
    var start = document.createElement("input");
    start.setAttribute("type", "number");
    start.setAttribute("placeholder", "Min");
    start.setAttribute("min", 0);
    start.setAttribute("max", 100);
    start.style.padding = "4px";
    start.style.width = "50%";
    start.style.boxSizing = "border-box";
    start.value = cell.getValue();
    function buildValues() {
        success({
            start: start.value,
            end: end.value,
        });
    }
    function keypress(e) {
        if (e.keyCode == 13) {
            buildValues();
        }

        if (e.keyCode == 27) {
            cancel();
        }
    }
    end = start.cloneNode();
    end.setAttribute("placeholder", "Max");
    start.addEventListener("change", buildValues);
    start.addEventListener("blur", buildValues);
    start.addEventListener("keydown", keypress);
    end.addEventListener("change", buildValues);
    end.addEventListener("blur", buildValues);
    end.addEventListener("keydown", keypress);
    container.appendChild(start);
    container.appendChild(end);
    return container;
};
function minMaxFilterFunction(headerValue, rowValue, rowData, filterParams) {
    if (rowValue) {
        if (headerValue.start != "") {
            if (headerValue.end != "") {
                return rowValue >= headerValue.start && rowValue <= headerValue.end;
            } else {
                return rowValue >= headerValue.start;
            }
        } else {
            if (headerValue.end != "") {
                return rowValue <= headerValue.end;
            }
        }
    }
    return true;
}

var table = [
    {tit:"30 second painter theme music", art:"DkuCook", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/30 second painter theme music.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/30-second-painter-theme-music\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"80s horror intro", art:"Emma M. Andersson", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/80s horror intro.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/retro-movie-theme-pack\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/licenses/by/3.0/\" target=\"_blank\" rel=\"noopener\">CC BY 3.0</a>"},
    {tit:"80s movie credits again", art:"Emma M. Andersson", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/80s movie credits again.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/retro-movie-theme-pack\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/licenses/by/3.0/\" target=\"_blank\" rel=\"noopener\">CC BY 3.0</a>"},
    {tit:"a cup of tea", art:"TAD", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/a cup of tea.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/lofi-compilation\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"a ghra", art:"Damiano Baldoni", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/a ghra.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/a-ghr%C3%A0-by-damiano-baldoni\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"a secret to tell you", art:"Deeppixel", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/a secret to tell you.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/a-secret-to-tell-you-mp3\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"adventure theme intro", art:"nene", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/adventure theme intro.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/adventure-intro-title-cinematic-epic\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"aerobics video intro", art:"Emma M. Andersson", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/aerobics video intro.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/retro-movie-theme-pack\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/licenses/by/3.0/\" target=\"_blank\" rel=\"noopener\">CC BY 3.0</a>"},
    {tit:"ambient piano", art:"tcarisland", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/ambient piano.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/ambient-piano\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"anti entity", art:"Tad", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/anti entity.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/anti-entity\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"anti entity.loop", art:"Tad", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/anti entity.loop.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/anti-entity\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"arcana.prev", art:"Tad, HitCtrl", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/arcana.prev.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/arcana-by-tadctrl-preview\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"artifact room", art:"Fupi", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/artifact room.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/artifact-room\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"astro", art:"BM_XT", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/astro.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/astro-bunker-destroyed-by-some-monsters-loopable\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"at night", art:"Stefan Grossmann", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/at night.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/free-music-pack-one-of-three\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"bartender", art:"TAD", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/bartender.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/lofi-compilation\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"battle", art:"RandomMind", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/battle.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/medieval-battle\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"battle-aboriginal", art:"Bobjt", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/battle-aboriginal.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/battle-aboriginal\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/licenses/by/3.0/\" target=\"_blank\" rel=\"noopener\">CC BY 3.0</a>"},
    {tit:"beautiful day", art:"Stefan Grossmann", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/beautiful day.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/free-music-pack-one-of-three\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"blip", art:"symphony", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/blip.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/blip\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"blithe", art:"Stefan Grossmann", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/blithe.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/free-music-pack-one-of-three\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"bone yard waltz.loop", art:"Wolfgang", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/bone yard waltz.loop.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/skeleton-waltz-theme\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"breathe - daylights", art:"onemansymphony", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/breathe - daylights.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/breathe-daylights\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"breathe - under the sea", art:"onemansymphony", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/breathe - under the sea.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/breathe-under-the-sea\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"cabin fever", art:"Alex McCulloch", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/cabin fever.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/cabin-fever\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"carefree", art:"Stefan Grossmann", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/carefree.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/free-music-pack-one-of-three\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"carousel", art:"ISAo", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/carousel.ogg\"></audio>", src:"<a href=\"https://opengameart.org/comment/84775\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://opengameart.org/content/oga-by-30-faq\" target=\"_blank\" rel=\"noopener\">OGA BY 3.0</a>"},
    {tit:"caryil the desert of dreams", art:"glitchart", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/caryil the desert of dreams.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/tausdei-vs-insydnis-remixed\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"http://creativecommons.org/licenses/by/3.0/\" target=\"_blank\" rel=\"noopener\">CC BY 3.0</a>"},
    {tit:"cat caffe", art:"TAD", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/cat caffe.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/lofi-compilation\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"cate", art:"You're Perfect Studio", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/cate.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/cate\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"chant", art:"christislord", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/chant.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/chant\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"chase", art:"wipics", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/chase.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/chase-1\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"chores", art:"Gradoa", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/chores.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/chores\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"daylight stinger", art:"SterlingRay", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/daylight stinger.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/daylight-stinger\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"http://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC 0</a>"},
    {tit:"forest river spirits", art:"Tausdei", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/forest river spirits.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/forest-river-spirits\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"http://creativecommons.org/licenses/by/3.0/\" target=\"_blank\" rel=\"noopener\">CC BY 3.0</a>"},
    {tit:"hopping harmony", art:"Magnesus", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/hopping harmony.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/hopping-harmony\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"hyperspace", art:"vitalezzz", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/hyperspace.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/hyperspace\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"http://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC 0</a>"},
    {tit:"i am sad today", art:"Alex_089", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/i am sad today.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/i-am-sad-today\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"io", art:"Alex McCulloch", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/io.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/io-0\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"http://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC 0</a>"},
    {tit:"mixed feelings", art:"StumpyStrust", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/mixed feelings.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/mixed-feelings\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"http://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC 0</a>"},
    {tit:"no time", art:"Tausdei", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/no time.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/no-time\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"http://opengameart.org/content/oga-by-30-faq\" target=\"_blank\" rel=\"noopener\">OGA BY 3.0</a>"},
    {tit:"rumble jungle", art:"Alex McCulloch", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/rumble jungle.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/rumble-jungle\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"http://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC 0</a>"},
    {tit:"sci-fi theme", art:"maou", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/sci-fi theme.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/sci-fi-theme-1\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"chromatic instrumental", art:"Alex McCulloch", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/chromatic instrumental.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/chromatic-instrumental\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"city of rain", art:"Scott Elliott", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/city of rain.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/city-of-rain\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"clouds.ambient", art:"symphony", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/clouds.ambient.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/clouds-5\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"clouds", art:"symphony", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/clouds.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/clouds-5\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"contact light", art:"symphony", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/contact light.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/contact-light\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"continuum", art:"Stefan Grossmann", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/continuum.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/free-music-pack-one-of-three\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"countryside", art:"TAD", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/countryside.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/lofi-compilation\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"crystalline", art:"Stefan Grossmann", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/crystalline.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/free-music-pack-one-of-three\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"cue", art:"TAD", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/cue.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/lofi-compilation\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"desolate mountain - solo trails", art:"Bobjt", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/desolate mountain - solo trails.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/desolate-mountain-solo-trails\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/licenses/by/3.0/\" target=\"_blank\" rel=\"noopener\">CC BY 3.0</a>"},
    {tit:"dorian heaven", art:"Alex McCulloch", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/dorian heaven.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/dorian-heaven\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"dream static", art:"symphony", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/dream static.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/dream-static\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"dreamscape", art:"Stefan Grossmann", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/dreamscape.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/free-music-pack-one-of-three\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"drifting", art:"symphony", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/drifting.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/drifting\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"driven", art:"Stefan Grossmann", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/driven.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/free-music-pack-one-of-three\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"dryads feast", art:"Tad, HitCtrl", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/dryads feast.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/dryads-feast\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"dryads feast.short", art:"Tad, HitCtrl", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/dryads feast.short.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/dryads-feast\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"early 90s movie", art:"Emma M. Andersson", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/early 90s movie.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/retro-movie-theme-pack\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/licenses/by/3.0/\" target=\"_blank\" rel=\"noopener\">CC BY 3.0</a>"},
    {tit:"early rain", art:"Pyoescd-Association", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/early rain.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/early-rain\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"eye of the storm", art:"Joth", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/eye of the storm.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/eye-of-the-storm\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"find nothing", art:"Tri-Tachyon", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/find nothing.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/soundscape-find-nothing\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"first snow", art:"Stefan Grossmann", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/first snow.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/free-music-pack-one-of-three\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"florist", art:"TAD", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/florist.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/lofi-compilation`\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"forest", art:"symphony", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/forest.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/forest-3\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"friends.loop", art:"Kim Lightyear", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/friends.loop.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/friends\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/licenses/by/3.0/\" target=\"_blank\" rel=\"noopener\">CC BY 3.0</a>"},
    {tit:"friends", art:"Kim Lightyear", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/friends.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/friends\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/licenses/by/3.0/\" target=\"_blank\" rel=\"noopener\">CC BY 3.0</a>"},
    {tit:"glory", art:"Stefan Grossmann", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/glory.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/free-music-pack-two-of-three\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"good morning", art:"You're Perfect Studio", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/good morning.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/good-morning\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"grim dacade", art:"Tad, HitCtrl", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/grim dacade.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/grim-decade\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/licenses/by/3.0/\" target=\"_blank\" rel=\"noopener\">CC BY 3.0</a>"},
    {tit:"guitar song", art:"Nicole Marie T", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/guitar song.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/guitar-song-loops-indie-game-seamless-looping-rpg-level-stage-etc\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/licenses/by/3.0/\" target=\"_blank\" rel=\"noopener\">CC BY 3.0</a>"},
    {tit:"halophiles", art:"RandomMind", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/halophiles.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/sea-and-river-wave-sounds\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"happy sad", art:"Stefan Grossmann", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/happy sad.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/free-music-pack-two-of-three\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"helix", art:"Stefan Grossmann", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/helix.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/free-music-pack-two-of-three\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"heroic moment", art:"Stefan Grossmann", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/heroic moment.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/free-music-pack-two-of-three\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"home sweet home", art:"Stefan Grossmann", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/home sweet home.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/free-music-pack-two-of-three\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"impatience", art:"Stefan Grossmann", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/impatience.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/free-music-pack-two-of-three\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"joy", art:"Stefan Grossmann", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/joy.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/free-music-pack-two-of-three\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"kings feast.loop", art:"RandomMind", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/kings feast.loop.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/medieval-kings-feast\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"kings feast", art:"RandomMind", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/kings feast.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/medieval-kings-feast\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"lament for a warriors soul", art:"RandomMynd", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/lament for a warriors soul.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/fantasy-lament-for-a-warriors-soul\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"lament for a warriors soul.reupload", art:"RandomMynd", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/lament for a warriors soul.reupload.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/fantasy-lament-for-a-warriors-soul\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"landurlaub", art:"joeBaxterWebb", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/landurlaub.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/landurlaub\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"leaves", art:"Stefan Grossmann", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/leaves.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/free-music-pack-two-of-three\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"levitate", art:"Stefan Grossmann", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/levitate.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/free-music-pack-two-of-three\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"licking wounds", art:"Viktor Kraus", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/licking wounds.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/licking-wounds\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/licenses/by/3.0/\" target=\"_blank\" rel=\"noopener\">CC BY 3.0</a>"},
    {tit:"loading", art:"Brandon Morris", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/loading.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/loading-screen-loop\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"loading.trem.loop", art:"Brandon Morris", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/loading.trem.loop.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/loading-screen-loop\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"loop", art:"Stefan Grossmann", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/loop.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/free-music-pack-two-of-three\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"magic moment", art:"Stefan Grossmann", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/magic moment.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/free-music-pack-two-of-three\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"market theme 1", art:"Geomancer", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/market theme 1.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/town-theme-1\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"melancholy", art:"Stefan Grossmann", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/melancholy.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/free-music-pack-two-of-three\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"melty - oga", art:"ISAo", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/melty - oga.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/emotional-strings-dramatic-battle-scene\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://opengameart.org/content/oga-by-30-faq\" target=\"_blank\" rel=\"noopener\">OGA BY 3.0</a>"},
    {tit:"morning birdsong", art:"brylie", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/morning birdsong.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/brylie-christopher-oxley-springtime-morning-birdsong\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"morning rain", art:"TAD", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/morning rain.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/lofi-compilation\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"moving higher", art:"David Kvistorf", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/moving higher.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/moving-higher\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"oceanside", art:"TAD", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/oceanside.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/lofi-compilation\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"odd", art:"Stefan Grossmann", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/odd.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/free-music-pack-two-of-three\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"ominous approach", art:"snapdragons", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/ominous approach.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/ominous-approach\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://www.gnu.org/licenses/gpl-3.0.html\" target=\"_blank\" rel=\"noopener\">GPL 3.0</a>"},
    {tit:"out in space", art:"David Kvistorf", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/out in space.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/out-in-space\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"out in space2", art:"Agecaf", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/out in space2.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/out-in-space-0\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"peace", art:"vitalezzz", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/peace.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/peace\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"piano.20200222.improv", art:"brylie", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/piano.20200222.improv.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/brylie-christopher-oxley-piano-2020-02-22\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"piano.20200419", art:"brylie", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/piano.20200419.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/brylie-christopher-oxley-piano-2020-04-19\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"pianocomp2", art:"symphony", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/pianocomp2.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/pianocomp2\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"pixel river", art:"Trevor Lentz", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/pixel river.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/pixel-river\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/licenses/by-sa/3.0/\" target=\"_blank\" rel=\"noopener\">CC SA 3.0</a>"},
    {tit:"rain falling on a cathedral", art:"Winger", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/rain falling on a cathedral.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/rain-0\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"rainy forest", art:"TAD", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/rainy forest.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/lofi-compilation\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"remnants of effervescence", art:"brylie", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/remnants of effervescence.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/remnants-of-effervescence\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"remnants of effervescence_2018-06-03", art:"brylie", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/remnants of effervescence_2018-06-03.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/remnants-of-effervescence\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"rpg the maw of the witches den.intro", art:"Hitctrl", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/rpg the maw of the witches den.intro.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/rpg-the-maw-of-the-witches-den\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/licenses/by/3.0/\" target=\"_blank\" rel=\"noopener\">CC BY 3.0</a>"},
    {tit:"rpg the maw of the witches den.loop", art:"Hitctrl", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/rpg the maw of the witches den.loop.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/rpg-the-maw-of-the-witches-den\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/licenses/by/3.0/\" target=\"_blank\" rel=\"noopener\">CC BY 3.0</a>"},
    {tit:"sad budi blues", art:"beansjam", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/sad budi blues.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/beansjam-sad-budi-blues\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"simple 80s piano movie theme", art:"Emma M. Andersson", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/simple 80s piano movie theme.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/retro-movie-theme-pack\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/licenses/by/3.0/\" target=\"_blank\" rel=\"noopener\">CC BY 3.0</a>"},
    {tit:"sky island", art:"symphony", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/sky island.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/medieval-the-old-tower-inn\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"solo violin", art:"ztn", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/solo violin.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/solo-violin\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"somniphobia", art:"symphony", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/somniphobia.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/somniphobia-0\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"storytrack_part1", art:"ztn", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/storytrack_part1.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/story-song\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"the bards tale.loop", art:"RandomMind", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/the bards tale.loop.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/medieval-the-bards-tale\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"the beautiful swan", art:"Frenchyboy", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/the beautiful swan.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/the-beautiful-swan\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"the end.piano", art:"TAD", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/the end.piano.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/the-end-dead-z-pandemic\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"the fall", art:"onemansymphony", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/the fall.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/the-fall\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"the lobster.beat", art:"TAD", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/the lobster.beat.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/the-lob-beat-ver\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/licenses/by/3.0/\" target=\"_blank\" rel=\"noopener\">CC BY 3.0</a>"},
    {tit:"the old tower inn", art:"RandomMind", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/the old tower inn.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/medieval-the-old-tower-inn\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"the pilgrimage", art:"Viktor Kraus", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/the pilgrimage.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/the-pilgrimage-0\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/licenses/by/3.0/\" target=\"_blank\" rel=\"noopener\">CC BY 3.0</a>"},
    {tit:"the rain gray", art:"adn_adn", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/the rain gray.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/the-rain-gray\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"the rising tide", art:"Hitctrl", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/the rising tide.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/the-rising-tide\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/licenses/by/3.0/\" target=\"_blank\" rel=\"noopener\">CC BY 3.0</a>"},
    {tit:"the tale of the fire", art:"Tausdei", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/the tale of the fire.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/the-tale-of-the-fire\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"thieves battle", art:"David Kvistorf", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/thieves battle.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/thieves-battle-theme\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"to be continued.original", art:"Bobjt", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/to be continued.original.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/to-be-continued\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/licenses/by/3.0/\" target=\"_blank\" rel=\"noopener\">CC BY 3.0</a>"},
    {tit:"uncharted planet", art:"onemansymphony", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/uncharted planet.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/uncharted-planet\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"vaata", art:"Fupi", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/vaata.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/vaata\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"village", art:"caterpillarmilk", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/village.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/village-in-the-wastes\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"vistula.short", art:"RandomMind", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/vistula.short.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/sea-and-river-wave-sounds\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"we are safe", art:"anthon", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/we are safe.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/we-are-safe\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"world map", art:"Scott Elliott", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/media_cumaean/main/world map.ogg\"></audio>", src:"<a href=\"https://opengameart.org/content/world-map-1\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"https://creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
];

var table = new Tabulator("#cumaean", {
    layout:"fitColumns",
    // pagination:"local",
    // paginationSize:20,
    // paginationSizeSelector:[10, 15, 20],
    movableColumns:true,
    paginationCounter:"rows",
    data:table,
    columns:[
        {title:"title", field:"tit", width:260, formatter:"html", headerFilter:"input"},
        {title:"artist", field:"art", width:180, formatter:"html", headerFilter:"input"},
        {title:"play", field:"play", width:360, formatter:"html"},
        {title:"source", field:"src", width:100, formatter:"html"},
        {title:"copyright", field:"cr", width:140, formatter:"html", headerFilter:"input"},
    ],
});

// https://stackoverflow.com/questions/19790506/multiple-audio-html-auto-stop-other-when-current-is-playing-with-javascript

document.addEventListener('play', function(e){
    var audios = document.getElementsByTagName('audio');
    for(var i = 0, len = audios.length; i < len;i++){
        if(audios[i] != e.target){
            audios[i].pause();
        }
    }
}, true);