var minMaxFilterEditor = function (cell, onRendered, success, cancel, editorParams) {
    var end;
    var container = document.createElement("span");
    var start = document.createElement("input");
    start.setAttribute("type", "number");
    start.setAttribute("placeholder", "Min");
    start.setAttribute("min", 0);
    start.setAttribute("max", 100);
    start.style.padding = "4px";
    start.style.width = "50%";
    start.style.boxSizing = "border-box";
    start.value = cell.getValue();
    function buildValues() {
        success({
            start: start.value,
            end: end.value,
        });
    }
    function keypress(e) {
        if (e.keyCode == 13) {
            buildValues();
        }

        if (e.keyCode == 27) {
            cancel();
        }
    }
    end = start.cloneNode();
    end.setAttribute("placeholder", "Max");
    start.addEventListener("change", buildValues);
    start.addEventListener("blur", buildValues);
    start.addEventListener("keydown", keypress);
    end.addEventListener("change", buildValues);
    end.addEventListener("blur", buildValues);
    end.addEventListener("keydown", keypress);
    container.appendChild(start);
    container.appendChild(end);
    return container;
};
function minMaxFilterFunction(headerValue, rowValue, rowData, filterParams) {
    if (rowValue) {
        if (headerValue.start != "") {
            if (headerValue.end != "") {
                return rowValue >= headerValue.start && rowValue <= headerValue.end;
            } else {
                return rowValue >= headerValue.start;
            }
        } else {
            if (headerValue.end != "") {
                return rowValue <= headerValue.end;
            }
        }
    }
    return true;
}

var table = [
    {tit:"30 second painter theme music", art:"DkuCook", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//30 second painter theme music.ogg\"></audio>", src:"<a href=\"//opengameart.org/content/30-second-painter-theme-music\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"http://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"80s horror intro", art:"Emma M. Andersson", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//80s horror intro.mp3\"></audio>", src:"<a href=\"//opengameart.org/content/retro-movie-theme-pack\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"http://creativecommons.org/licenses/by/3.0/\" target=\"_blank\" rel=\"noopener\">CC BY 3.0</a>"},
    {tit:"80s movie credits again", art:"Emma M. Andersson", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//80s movie credits again.mp3\"></audio>", src:"<a href=\"//opengameart.org/content/retro-movie-theme-pack\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"http://creativecommons.org/licenses/by/3.0/\" target=\"_blank\" rel=\"noopener\">CC BY 3.0</a>"},
    {tit:"a cup of tea", art:"TAD", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//a cup of tea.mp3\"></audio>", src:"<a href=\"//opengameart.org/content/lofi-compilation\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"http://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"a ghra", art:"Damiano Baldoni", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//a ghra.mp3\"></audio>", src:"<a href=\"//opengameart.org/content/a-ghr%C3%A0-by-damiano-baldoni\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"//creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"a secret to tell you", art:"Deeppixel", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//a secret to tell you.mp3\"></audio>", src:"<a href=\"//opengameart.org/content/a-secret-to-tell-you-mp3\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"http://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"adventure theme intro", art:"nene", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//adventure theme intro.ogg\"></audio>", src:"<a href=\"//opengameart.org/content/adventure-intro-title-cinematic-epic\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"http://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"aerobics video intro", art:"Emma M. Andersson", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//aerobics video intro.mp3\"></audio>", src:"<a href=\"//opengameart.org/content/retro-movie-theme-pack\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"http://creativecommons.org/licenses/by/3.0/\" target=\"_blank\" rel=\"noopener\">CC BY 3.0</a>"},
    {tit:"ambient piano", art:"tcarisland", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//ambient piano.mp3\"></audio>", src:"<a href=\"//opengameart.org/content/ambient-piano\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"//creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"anti entity.loop", art:"Tad", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//anti entity.loop.ogg\"></audio>", src:"<a href=\"//opengameart.org/content/anti-entity\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"//creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"anti entity", art:"Tad", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//anti entity.ogg\"></audio>", src:"<a href=\"//opengameart.org/content/anti-entity\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"//creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"arcana.prev", art:"Tad, HitCtrl", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//arcana.prev.mp3\"></audio>", src:"<a href=\"//opengameart.org/content/arcana-by-tadctrl-preview\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"//creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"artifact room", art:"Fupi", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//artifact room.ogg\"></audio>", src:"<a href=\"//opengameart.org/content/artifact-room\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"http://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"astro", art:"BM_XT", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//astro.mp3\"></audio>", src:"<a href=\"//opengameart.org/content/astro-bunker-destroyed-by-some-monsters-loopable\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"//creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"at night", art:"Stefan Grossmann", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//at night.ogg\"></audio>", src:"<a href=\"//opengameart.org/content/free-music-pack-one-of-three\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"//creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"bartender", art:"TAD", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//bartender.mp3\"></audio>", src:"<a href=\"//opengameart.org/content/lofi-compilation\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"http://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"battle", art:"RandomMind", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//battle.ogg\"></audio>", src:"<a href=\"//opengameart.org/content/medieval-battle\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"http://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"battle-aboriginal", art:"Bobjt", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//battle-aboriginal.mp3\"></audio>", src:"<a href=\"//opengameart.org/content/battle-aboriginal\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"http://creativecommons.org/licenses/by/3.0/\" target=\"_blank\" rel=\"noopener\">CC BY 3.0</a>"},
    {tit:"beautiful day", art:"Stefan Grossmann", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//beautiful day.ogg\"></audio>", src:"<a href=\"//opengameart.org/content/free-music-pack-one-of-three\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"//creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"blip", art:"symphony", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//blip.mp3\"></audio>", src:"<a href=\"//opengameart.org/content/blip\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"http://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"blithe", art:"Stefan Grossmann", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//blithe.ogg\"></audio>", src:"<a href=\"//opengameart.org/content/free-music-pack-one-of-three\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"//creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"bone yard waltz.loop", art:"Wolfgang", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//bone yard waltz.loop.ogg\"></audio>", src:"<a href=\"//opengameart.org/content/skeleton-waltz-theme\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"//creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"breathe - daylights", art:"onemansymphony", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//breathe - daylights.mp3\"></audio>", src:"<a href=\"//opengameart.org/content/breathe-daylights\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"//creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"breathe - under the sea", art:"onemansymphony", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//breathe - under the sea.mp3\"></audio>", src:"<a href=\"//opengameart.org/content/breathe-under-the-sea\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"//creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"cabin fever", art:"Pro Sensory", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//cabin fever.mp3\"></audio>", src:"<a href=\"//opengameart.org/content/cabin-fever\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"http://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"carefree", art:"Stefan Grossmann", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//carefree.ogg\"></audio>", src:"<a href=\"//opengameart.org/content/free-music-pack-one-of-three\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"//creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"carousel", art:"ISAo", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//carousel.mp3\"></audio>", src:"<a href=\"//opengameart.org/comment/84775\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"http://opengameart.org/content/oga-by-30-faq\" target=\"_blank\" rel=\"noopener\">OGA BY 3.0</a>"},
    {tit:"cat caffe", art:"TAD", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//cat caffe.mp3\"></audio>", src:"<a href=\"//opengameart.org/content/lofi-compilation\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"http://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"cate", art:"You're Perfect Studio", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//cate.ogg\"></audio>", src:"<a href=\"//opengameart.org/content/cate\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"//creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"chant", art:"christislord", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//chant.mp3\"></audio>", src:"<a href=\"//opengameart.org/content/chant\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"http://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"chase", art:"wipics", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//chase.ogg\"></audio>", src:"<a href=\"//opengameart.org/content/chase-1\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"http://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"chores", art:"Gradoa", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//chores.ogg\"></audio>", src:"<a href=\"//opengameart.org/content/chores\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"http://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"chromatic instrumental", art:"Pro Sensory", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//chromatic instrumental.mp3\"></audio>", src:"<a href=\"//opengameart.org/content/chromatic-instrumental\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"http://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"city of rain", art:"Scott Elliott", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//city of rain.ogg\"></audio>", src:"<a href=\"//opengameart.org/content/city-of-rain\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"//creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"clouds.ambient", art:"symphony", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//clouds.ambient.ogg\"></audio>", src:"<a href=\"//opengameart.org/content/clouds-5\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"//creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"clouds", art:"symphony", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//clouds.mp3\"></audio>", src:"<a href=\"//opengameart.org/content/clouds-5\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"//creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"contact light", art:"symphony", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//contact light.ogg\"></audio>", src:"<a href=\"//opengameart.org/content/contact-light\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"//creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"continuum", art:"Stefan Grossmann", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//continuum.ogg\"></audio>", src:"<a href=\"//opengameart.org/content/free-music-pack-one-of-three\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"//creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"countryside", art:"TAD", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//countryside.mp3\"></audio>", src:"<a href=\"//opengameart.org/content/lofi-compilation\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"http://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"crystalline", art:"Stefan Grossmann", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//crystalline.ogg\"></audio>", src:"<a href=\"//opengameart.org/content/free-music-pack-one-of-three\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"//creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"cue", art:"TAD", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//cue.mp3\"></audio>", src:"<a href=\"//opengameart.org/content/lofi-compilation\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"http://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"desolate mountain - solo trails", art:"Bobjt", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//desolate mountain - solo trails.mp3\"></audio>", src:"<a href=\"//opengameart.org/content/desolate-mountain-solo-trails\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"http://creativecommons.org/licenses/by/3.0/\" target=\"_blank\" rel=\"noopener\">CC BY 3.0</a>"},
    {tit:"dorian heaven", art:"Alex McCulloch", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//dorian heaven.mp3\"></audio>", src:"<a href=\"//opengameart.org/content/dorian-heaven\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"http://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"dream static", art:"symphony", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//dream static.mp3\"></audio>", src:"<a href=\"//opengameart.org/content/dream-static\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"http://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"dreamscape", art:"Stefan Grossmann", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//dreamscape.ogg\"></audio>", src:"<a href=\"//opengameart.org/content/free-music-pack-one-of-three\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"//creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"drifting", art:"symphony", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//drifting.mp3\"></audio>", src:"<a href=\"//opengameart.org/content/drifting\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"http://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"driven", art:"Stefan Grossmann", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//driven.ogg\"></audio>", src:"<a href=\"//opengameart.org/content/free-music-pack-one-of-three\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"//creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"dryads feast", art:"Tad, HitCtrl", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//dryads feast.mp3\"></audio>", src:"<a href=\"//opengameart.org/content/dryads-feast\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"//creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"dryads feast.short", art:"Tad, HitCtrl", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//dryads feast.short.mp3\"></audio>", src:"<a href=\"//opengameart.org/content/dryads-feast\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"//creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"early 90s movie", art:"Emma M. Andersson", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//early 90s movie.mp3\"></audio>", src:"<a href=\"//opengameart.org/content/retro-movie-theme-pack\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"http://creativecommons.org/licenses/by/3.0/\" target=\"_blank\" rel=\"noopener\">CC BY 3.0</a>"},
    {tit:"early rain", art:"Pyoescd-Association", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//early rain.mp3\"></audio>", src:"<a href=\"//opengameart.org/content/early-rain\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"//creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"eye of the storm", art:"Joth", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//eye of the storm.mp3\"></audio>", src:"<a href=\"//opengameart.org/content/eye-of-the-storm\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"http://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"find nothing", art:"Tri-Tachyon", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//find nothing.mp3\"></audio>", src:"<a href=\"//opengameart.org/content/soundscape-find-nothing\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"//creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"first snow", art:"Stefan Grossmann", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//first snow.ogg\"></audio>", src:"<a href=\"//opengameart.org/content/free-music-pack-one-of-three\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"//creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"florist", art:"TAD", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//florist.mp3\"></audio>", src:"<a href=\"//opengameart.org/content/lofi-compilation`\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"http://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"forest", art:"symphony", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//forest.mp3\"></audio>", src:"<a href=\"//opengameart.org/content/forest-3\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"http://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"friends.loop", art:"Kim Lightyear", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//friends.loop.ogg\"></audio>", src:"<a href=\"//opengameart.org/content/friends\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"http://creativecommons.org/licenses/by/3.0/\" target=\"_blank\" rel=\"noopener\">CC BY 3.0</a>"},
    {tit:"friends", art:"Kim Lightyear", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//friends.ogg\"></audio>", src:"<a href=\"//opengameart.org/content/friends\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"http://creativecommons.org/licenses/by/3.0/\" target=\"_blank\" rel=\"noopener\">CC BY 3.0</a>"},
    {tit:"glory", art:"Stefan Grossmann", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//glory.ogg\"></audio>", src:"<a href=\"//opengameart.org/content/free-music-pack-two-of-three\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"//creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"good morning", art:"You're Perfect Studio", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//good morning.mp3\"></audio>", src:"<a href=\"//opengameart.org/content/good-morning\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"//creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"grim dacade", art:"Tad, HitCtrl", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//grim dacade.mp3\"></audio>", src:"<a href=\"//opengameart.org/content/grim-decade\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"http://creativecommons.org/licenses/by/3.0/\" target=\"_blank\" rel=\"noopener\">CC BY 3.0</a>"},
    {tit:"guitar song", art:"Nicole Marie T", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//guitar song.ogg\"></audio>", src:"<a href=\"//opengameart.org/content/guitar-song-loops-indie-game-seamless-looping-rpg-level-stage-etc\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"http://creativecommons.org/licenses/by/3.0/\" target=\"_blank\" rel=\"noopener\">CC BY 3.0</a>"},
    {tit:"halophiles", art:"RandomMind", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//halophiles.ogg\"></audio>", src:"<a href=\"//opengameart.org/content/sea-and-river-wave-sounds\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"http://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"happy sad", art:"Stefan Grossmann", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//happy sad.ogg\"></audio>", src:"<a href=\"//opengameart.org/content/free-music-pack-two-of-three\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"//creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"helix", art:"Stefan Grossmann", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//helix.ogg\"></audio>", src:"<a href=\"//opengameart.org/content/free-music-pack-two-of-three\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"//creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"heroic moment", art:"Stefan Grossmann", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//heroic moment.ogg\"></audio>", src:"<a href=\"//opengameart.org/content/free-music-pack-two-of-three\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"//creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"home sweet home", art:"Stefan Grossmann", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//home sweet home.ogg\"></audio>", src:"<a href=\"//opengameart.org/content/free-music-pack-two-of-three\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"//creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"impatience", art:"Stefan Grossmann", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//impatience.ogg\"></audio>", src:"<a href=\"//opengameart.org/content/free-music-pack-two-of-three\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"//creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"joy", art:"Stefan Grossmann", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//joy.ogg\"></audio>", src:"<a href=\"//opengameart.org/content/free-music-pack-two-of-three\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"//creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"kings feast.loop", art:"RandomMind", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//kings feast.loop.ogg\"></audio>", src:"<a href=\"//opengameart.org/content/medieval-kings-feast\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"http://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"kings feast", art:"RandomMind", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//kings feast.mp3\"></audio>", src:"<a href=\"//opengameart.org/content/medieval-kings-feast\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"http://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"lament for a warriors soul", art:"RandomMynd", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//lament for a warriors soul.mp3\"></audio>", src:"<a href=\"//opengameart.org/content/fantasy-lament-for-a-warriors-soul\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"http://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"lament for a warriors soul.reupload", art:"RandomMynd", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//lament for a warriors soul.reupload.mp3\"></audio>", src:"<a href=\"//opengameart.org/content/fantasy-lament-for-a-warriors-soul\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"http://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"landurlaub", art:"joeBaxterWebb", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//landurlaub.mp3\"></audio>", src:"<a href=\"//opengameart.org/content/landurlaub\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"//creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"leaves", art:"Stefan Grossmann", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//leaves.ogg\"></audio>", src:"<a href=\"//opengameart.org/content/free-music-pack-two-of-three\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"//creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"levitate", art:"Stefan Grossmann", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//levitate.ogg\"></audio>", src:"<a href=\"//opengameart.org/content/free-music-pack-two-of-three\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"//creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"licking wounds", art:"Viktor Kraus", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//licking wounds.ogg\"></audio>", src:"<a href=\"//opengameart.org/content/licking-wounds\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"http://creativecommons.org/licenses/by/3.0/\" target=\"_blank\" rel=\"noopener\">CC BY 3.0</a>"},
    {tit:"loading", art:"Brandon Morris", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//loading.ogg\"></audio>", src:"<a href=\"//opengameart.org/content/loading-screen-loop\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"http://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"loading.trem.loop", art:"Brandon Morris", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//loading.trem.loop.ogg\"></audio>", src:"<a href=\"//opengameart.org/content/loading-screen-loop\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"http://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"loop", art:"Stefan Grossmann", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//loop.ogg\"></audio>", src:"<a href=\"//opengameart.org/content/free-music-pack-two-of-three\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"//creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"magic moment", art:"Stefan Grossmann", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//magic moment.ogg\"></audio>", src:"<a href=\"//opengameart.org/content/free-music-pack-two-of-three\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"//creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"market theme 1", art:"Geomancer", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//market theme 1.mp3\"></audio>", src:"<a href=\"//opengameart.org/content/town-theme-1\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"http://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"melancholy", art:"Stefan Grossmann", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//melancholy.ogg\"></audio>", src:"<a href=\"//opengameart.org/content/free-music-pack-two-of-three\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"//creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"melty - oga", art:"ISAo", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//melty - oga.mp3\"></audio>", src:"<a href=\"//opengameart.org/content/emotional-strings-dramatic-battle-scene\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"http://opengameart.org/content/oga-by-30-faq\" target=\"_blank\" rel=\"noopener\">OGA BY 3.0</a>"},
    {tit:"morning birdsong", art:"brylie", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//morning birdsong.ogg\"></audio>", src:"<a href=\"//opengameart.org/content/brylie-christopher-oxley-springtime-morning-birdsong\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"//creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"morning rain", art:"TAD", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//morning rain.mp3\"></audio>", src:"<a href=\"//opengameart.org/content/lofi-compilation\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"http://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"moving higher", art:"David Kvistorf", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//moving higher.mp3\"></audio>", src:"<a href=\"//opengameart.org/content/moving-higher\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"http://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"oceanside", art:"TAD", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//oceanside.mp3\"></audio>", src:"<a href=\"//opengameart.org/content/lofi-compilation\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"http://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"odd", art:"Stefan Grossmann", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//odd.ogg\"></audio>", src:"<a href=\"//opengameart.org/content/free-music-pack-two-of-three\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"//creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"ominous approach", art:"snapdragons", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//ominous approach.ogg\"></audio>", src:"<a href=\"//opengameart.org/content/ominous-approach\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"http://www.gnu.org/licenses/gpl-3.0.html\" target=\"_blank\" rel=\"noopener\">GPL 3.0</a>"},
    {tit:"out in space", art:"David Kvistorf", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//out in space.ogg\"></audio>", src:"<a href=\"//opengameart.org/content/out-in-space\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"http://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"out in space2", art:"Agecaf", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//out in space2.ogg\"></audio>", src:"<a href=\"//opengameart.org/content/out-in-space-0\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"http://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"peace", art:"vitalezzz", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//peace.ogg\"></audio>", src:"<a href=\"//opengameart.org/content/peace\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"//creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"piano.20200222.improv", art:"brylie", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//piano.20200222.improv.ogg\"></audio>", src:"<a href=\"//opengameart.org/content/brylie-christopher-oxley-piano-2020-02-22\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"//creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"piano.20200419", art:"brylie", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//piano.20200419.ogg\"></audio>", src:"<a href=\"//opengameart.org/content/brylie-christopher-oxley-piano-2020-04-19\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"//creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"pianocomp2", art:"symphony", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//pianocomp2.mp3\"></audio>", src:"<a href=\"//opengameart.org/content/pianocomp2\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"http://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"pixel river", art:"Trevor Lentz", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//pixel river.ogg\"></audio>", src:"<a href=\"//opengameart.org/content/pixel-river\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"http://creativecommons.org/licenses/by-sa/3.0/\" target=\"_blank\" rel=\"noopener\">CC SA 3.0</a>"},
    {tit:"rain falling on a cathedral", art:"Winger", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//rain falling on a cathedral.ogg\"></audio>", src:"<a href=\"//opengameart.org/content/rain-0\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"//creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"rainy forest", art:"TAD", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//rainy forest.mp3\"></audio>", src:"<a href=\"//opengameart.org/content/lofi-compilation\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"http://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"remnants of effervescence", art:"brylie", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//remnants of effervescence.ogg\"></audio>", src:"<a href=\"//opengameart.org/content/remnants-of-effervescence\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"http://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"remnants of effervescence_2018-06-03", art:"brylie", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//remnants of effervescence_2018-06-03.ogg\"></audio>", src:"<a href=\"//opengameart.org/content/remnants-of-effervescence\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"http://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"rpg the maw of the witches den.intro", art:"Hitctrl", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//rpg the maw of the witches den.intro.mp3\"></audio>", src:"<a href=\"//opengameart.org/content/rpg-the-maw-of-the-witches-den\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"http://creativecommons.org/licenses/by/3.0/\" target=\"_blank\" rel=\"noopener\">CC BY 3.0</a>"},
    {tit:"rpg the maw of the witches den.loop", art:"Hitctrl", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//rpg the maw of the witches den.loop.mp3\"></audio>", src:"<a href=\"//opengameart.org/content/rpg-the-maw-of-the-witches-den\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"http://creativecommons.org/licenses/by/3.0/\" target=\"_blank\" rel=\"noopener\">CC BY 3.0</a>"},
    {tit:"sad budi blues", art:"beansjam", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//sad budi blues.ogg\"></audio>", src:"<a href=\"//opengameart.org/content/beansjam-sad-budi-blues\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"//creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"simple 80s piano movie theme", art:"Emma M. Andersson", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//simple 80s piano movie theme.mp3\"></audio>", src:"<a href=\"//opengameart.org/content/retro-movie-theme-pack\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"http://creativecommons.org/licenses/by/3.0/\" target=\"_blank\" rel=\"noopener\">CC BY 3.0</a>"},
    {tit:"sky island", art:"symphony", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//sky island.ogg\"></audio>", src:"<a href=\"//opengameart.org/content/medieval-the-old-tower-inn\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"http://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"solo violin", art:"ztn", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//solo violin.ogg\"></audio>", src:"<a href=\"//opengameart.org/content/solo-violin\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"http://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"somniphobia", art:"symphony", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//somniphobia.ogg\"></audio>", src:"<a href=\"//opengameart.org/content/somniphobia-0\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"//creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"storytrack_part1", art:"ztn", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//storytrack_part1.ogg\"></audio>", src:"<a href=\"//opengameart.org/content/story-song\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"http://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"the bards tale.loop", art:"RandomMind", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//the bards tale.loop.ogg\"></audio>", src:"<a href=\"//opengameart.org/content/medieval-the-bards-tale\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"http://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"the beautiful swan", art:"Frenchyboy", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//the beautiful swan.ogg\"></audio>", src:"<a href=\"//opengameart.org/content/the-beautiful-swan\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"http://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"the end.piano", art:"TAD", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//the end.piano.mp3\"></audio>", src:"<a href=\"//opengameart.org/content/the-end-dead-z-pandemic\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"http://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"the fall", art:"onemansymphony", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//the fall.mp3\"></audio>", src:"<a href=\"//opengameart.org/content/the-fall\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"//creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"the lobster.beat", art:"TAD", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//the lobster.beat.mp3\"></audio>", src:"<a href=\"//opengameart.org/content/the-lob-beat-ver\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"http://creativecommons.org/licenses/by/3.0/\" target=\"_blank\" rel=\"noopener\">CC BY 3.0</a>"},
    {tit:"the old tower inn", art:"RandomMind", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//the old tower inn.ogg\"></audio>", src:"<a href=\"//opengameart.org/content/medieval-the-old-tower-inn\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"http://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"the pilgrimage", art:"Viktor Kraus", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//the pilgrimage.ogg\"></audio>", src:"<a href=\"//opengameart.org/content/the-pilgrimage-0\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"http://creativecommons.org/licenses/by/3.0/\" target=\"_blank\" rel=\"noopener\">CC BY 3.0</a>"},
    {tit:"the rain gray", art:"adn_adn", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//the rain gray.mp3\"></audio>", src:"<a href=\"//opengameart.org/content/the-rain-gray\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"//creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"the rising tide", art:"Hitctrl", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//the rising tide.mp3\"></audio>", src:"<a href=\"//opengameart.org/content/the-rising-tide\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"http://creativecommons.org/licenses/by/3.0/\" target=\"_blank\" rel=\"noopener\">CC BY 3.0</a>"},
    {tit:"the tale of the fire", art:"Tausdei", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//the tale of the fire.mp3\"></audio>", src:"<a href=\"//opengameart.org/content/the-tale-of-the-fire\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"//creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"thieves battle", art:"David Kvistorf", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//thieves battle.mp3\"></audio>", src:"<a href=\"//opengameart.org/content/thieves-battle-theme\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"http://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"to be continued.original", art:"Bobjt", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//to be continued.original.mp3\"></audio>", src:"<a href=\"//opengameart.org/content/to-be-continued\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"http://creativecommons.org/licenses/by/3.0/\" target=\"_blank\" rel=\"noopener\">CC BY 3.0</a>"},
    {tit:"uncharted planet", art:"onemansymphony", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//uncharted planet.mp3\"></audio>", src:"<a href=\"//opengameart.org/content/uncharted-planet\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"//creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"vaata", art:"Fupi", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//vaata.ogg\"></audio>", src:"<a href=\"//opengameart.org/content/vaata\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"http://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"village", art:"caterpillarmilk", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//village.mp3\"></audio>", src:"<a href=\"//opengameart.org/content/village-in-the-wastes\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"//creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"vistula.short", art:"RandomMind", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//vistula.short.mp3\"></audio>", src:"<a href=\"//opengameart.org/content/sea-and-river-wave-sounds\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"http://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener\">CC ZERO 1.0</a>"},
    {tit:"we are safe", art:"anthon", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//we are safe.ogg\"></audio>", src:"<a href=\"//opengameart.org/content/we-are-safe\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"//creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
    {tit:"world map", art:"Scott Elliott", play:"<audio controls preload=\"none\" src=\"https://raw.githubusercontent.com/scillidan/private_cdn/main/cumaean//world map.mp3\"></audio>", src:"<a href=\"//opengameart.org/content/world-map-1\" target=\"_blank\" rel=\"noopener\">Link</a>", cr:"<a href=\"//creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY 4.0</a>"},
];

var table = new Tabulator("#cumaean", {
    layout:"fitColumns",
    // pagination:"local",
    // paginationSize:20,
    // paginationSizeSelector:[10, 15, 20],
    movableColumns:true,
    paginationCounter:"rows",
    data:table,
    columns:[
        {title:"title", field:"tit", width:260, formatter:"html", headerFilter:"input"},
        {title:"artist", field:"art", width:180, formatter:"html", headerFilter:"input"},
        {title:"play", field:"play", width:360, formatter:"html"},
        {title:"source", field:"src", width:100, formatter:"html"},
        {title:"copyright", field:"cr", width:140, formatter:"html", headerFilter:"input"},
    ],
});

// https://stackoverflow.com/questions/19790506/multiple-audio-html-auto-stop-other-when-current-is-playing-with-javascript

document.addEventListener('play', function(e){
    var audios = document.getElementsByTagName('audio');
    for(var i = 0, len = audios.length; i < len;i++){
        if(audios[i] != e.target){
            audios[i].pause();
        }
    }
}, true);